### ISSUE TITLE
Home page of the example site doesn't have any content

### ISSUE THREAD

**Issue by joeroe** [joeroe/risotto#17]
It should have a version of the theme's README, but I don't fancy updating that all the time.

**Comment by 33nano** [comment]
> It should have a version of the theme's README, but I don't fancy updating that all the time.

Hey Joe, absolutely love your theme. I tried several other Hugo themes, but i settled on this one for its beauty and simplicity. I definitely would like to have something on the homepage, like an image or some text. I figured it would be faster to ask you about the whereabouts of such file since you made it. This is my [site](https://33nano/xyz] , i am still working on it and off course the source [code](https://github.com/33nano/33nano.github.io) .  Thanks Joe, you're awesome!

**Comment by joeroe** [comment]
Thank you very much @33nano. You can add content to the homepage by creating `content/_index.md`. Apart from the special location, it behaves like a regular hugo page. 

For example, https://github.com/sslarch/sslarch.github.io/blob/master/content/_index.md generates https://sslarch.github.io/.

More information here: https://gohugo.io/content-management/organization/#index-pages-_indexmd
